name: 🐛 Bug Report
description: Create a Bug Report
title: "🐛 [Bug Report]: "
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Hello, thanks for taking the time to fill out this bug report!

        Before you begin, **please ensure there is no existing open or closed issue related to your report**.

        ---

  - type: input
    id: cms-version
    attributes:
      label: BlizzCMS Version
      description: e.g. 1.1.0
    validations:
      required: true

  - type: dropdown
    id: emulator
    attributes:
      label: Emulator
      description: Which emulator are you using?
      multiple: false
      options:
        - AzerothCore
        - CMaNGOS
        - MaNGOS
        - TrinityCore
        - Other
    validations:
      required: true

  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: Which PHP version are you using?
      multiple: false
      options:
        - PHP 7.4
        - PHP 8.0
        - PHP 8.1
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      description: Which operating system are you using?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: dropdown
    id: web-server
    attributes:
      label: Web server
      description: Which web server are you using?
      multiple: false
      options:
        - Apache
        - Nginx
        - Other
    validations:
      required: true

  - type: input
    id: database
    attributes:
      label: Database
      description: e.g. MySQL 5.7, MariaDB 10.6
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue in detail.
    validations:
      required: true
  
  - type: textarea
    id: issue-reproduce
    attributes:
      label: How can the issue be reproduced?
      description: Describe steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: issue-screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots here or share links.
