name: 💡 Feature Request
description: Create a Feature Request
title: "💡 [Feature Request]: "
labels: ['suggest']
body:
  - type: markdown
    attributes:
      value: |
        Hello, thank you for taking the time to give ideas for the project!

        Before you begin, **please ensure there is no existing open or closed feature request related to your request**.

        ---

  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: Describe the feature request in detail explaining its implementation and how it would work.
    validations:
      required: true

  - type: textarea
    id: feature-purpose
    attributes:
      label: Feature Purpose
      description: Describe the purpose of this feature request.
    validations:
      required: true

  - type: textarea
    id: extra-info
    attributes:
      label: Additional information
      description: Provide screenshots here or share links.
